### ISSUE TITLE
Room id is not recognized

### ISSUE THREAD

**Issue by ssbarnea** [fadenb/Matrix-Chat-Message#113]
While trying this action, I quickly got an error about an invalid room ID, which I am sure is correct.

The test workflow can be seen at https://github.com/ansible-community/devtools/blob/main/.github/workflows/notify.yml

Any idea about what went wrong? I kinda find it funny that the  room id is not displayed in log but there is a very long stacktrace. AFAIK, room id is not really a secret.

```
Error sending event M_UNRECOGNIZED: Unrecognized request
    at parseErrorResponse (/home/runner/work/_actions/fadenb/matrix-chat-message/v0.0.6/dist/index.js:51078:13)
homeserver: matrix.org
    at /home/runner/work/_actions/fadenb/matrix-chat-message/v0.0.6/dist/index.js:51033:17
channel: 
    at Request._callback (/home/runner/work/_actions/fadenb/matrix-chat-message/v0.0.6/dist/index.js:50967:9)
token: ***
    at Request.self.callback (/home/runner/work/_actions/fadenb/matrix-chat-message/v0.0.6/dist/index.js:71728:22)
message: 
    at Request.emit (events.js:210:5)
messagetype: m.notice
    at Request.<anonymous> (/home/runner/work/_actions/fadenb/matrix-chat-message/v0.0.6/dist/index.js:72697:10)
sendEvent of type m.room.message in  with txnId m1636115815079.0
    at Request.emit (events.js:210:5)
Error: M_UNRECOGNIZED: Unrecognized request
    at IncomingMessage.<anonymous> (/home/runner/work/_actions/fadenb/matrix-chat-message/v0.0.6/dist/index.js:72619:12)
    at Object.onceWrapper (events.js:299:28)
    at IncomingMessage.emit (events.js:215:7)
(node:2074) UnhandledPromiseRejectionWarning: M_UNKNOWN:  was not legal room ID or room alias
    at parseErrorResponse (/home/runner/work/_actions/fadenb/matrix-chat-message/v0.0.6/dist/index.js:51078:13)
    at /home/runner/work/_actions/fadenb/matrix-chat-message/v0.0.6/dist/index.js:51033:17
    at Request._callback (/home/runner/work/_actions/fadenb/matrix-chat-message/v0.0.6/dist/index.js:50967:9)
    at Request.self.callback (/home/runner/work/_actions/fadenb/matrix-chat-message/v0.0.6/dist/index.js:71728:22)
    at Request.emit (events.js:210:5)
    at Request.<anonymous> (/home/runner/work/_actions/fadenb/matrix-chat-message/v0.0.6/dist/index.js:72697:10)
    at Request.emit (events.js:210:5)
    at IncomingMessage.<anonymous> (/home/runner/work/_actions/fadenb/matrix-chat-message/v0.0.6/dist/index.js:72619:12)
    at Object.onceWrapper (events.js:299:28)
    at IncomingMessage.emit (events.js:215:7)
(node:2074) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2074) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by fadenb** [comment]
Hey,
I just wanted to let you know that I will definitively not have time to look into that issue this or next week.
If you find the cause on your own in the meantime, I would be happy to merge a fix.

**Comment by fadenb** [comment]
Hey @ssbarnea,

sorry for the long wait. Just took some time to test but I am unable to reproduce the issue. I used [an action](https://github.com/fadenb/matrix-chat-message-test/blob/master/.github/workflows/matrix-chat-message.yml) in my [test repository](https://github.com/fadenb/matrix-chat-message-test) for this.
More specifically I triggered the action in that repository using the latest release of the action (`v0.0.6`, same that you have been using) and the latest commit on the master branch. Both worked fine (after I made sure that my access token was correct 😉).

![image](https://user-images.githubusercontent.com/878822/147355574-1447892d-61c9-47fe-8afc-12fa3c85ec0e.png)


See https://github.com/fadenb/matrix-chat-message-test/runs/4626989078?check_suite_focus=true and https://github.com/fadenb/matrix-chat-message-test/runs/4626994453?check_suite_focus=true for the output of the action.

**Comment by fadenb** [comment]
I am closing this as stale.
Ping me if you can reproduce the issue and I am happy to take a look :)
